# Generated by Django 3.2 on 2021-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_contacto_avisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_registro', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apaterno', models.CharField(max_length=20)),
                ('amaterno', models.CharField(max_length=20)),
                ('rut', models.BigIntegerField()),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(max_length=30)),
                ('deuda', models.CharField(blank=True, max_length=1, null=True)),
                ('fiado_idfiado', models.CharField(blank=True, db_column='fiado_idFiado', max_length=1, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
