# Generated by Django 3.2 on 2021-06-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_measumerement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measumerement',
            old_name='destionation',
            new_name='destination',
        ),
    ]
