# Generated by Django 3.2 on 2021-06-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_destionation_measumerement_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measumerement',
        ),
    ]
