# Generated by Django 3.2 on 2021-07-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_measumerement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('numboleta', models.AutoField(db_column='numBoleta', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('deuda', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodBar',
            fields=[
                ('idempresa', models.IntegerField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('producto_familia', models.IntegerField()),
                ('producto_fechavenc', models.IntegerField(db_column='producto_fechaVenc')),
                ('producto_tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'cod_bar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleboleta',
            fields=[
                ('iddetalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleboleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallefactura',
            fields=[
                ('iddetalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detallefactura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('iddiscrepancia', models.AutoField(db_column='idDiscrepancia', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('informacionadicional', models.CharField(blank=True, db_column='informacionAdicional', max_length=60, null=True)),
            ],
            options={
                'db_table': 'discrepancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apaterno', models.CharField(max_length=15)),
                ('amaterno', models.CharField(blank=True, max_length=15, null=True)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('fechacontrato', models.DateField(db_column='fechaContrato')),
                ('fechatermino', models.DateField(db_column='fechaTermino')),
                ('cargo', models.CharField(max_length=20)),
                ('sueldo', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('rubro', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numfactura', models.AutoField(db_column='numFactura', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('costo', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idfamilia', models.IntegerField(db_column='idFamilia', primary_key=True, serialize=False)),
                ('decripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('idfiado', models.AutoField(db_column='idFiado', primary_key=True, serialize=False)),
                ('monto', models.CharField(blank=True, max_length=45, null=True)),
                ('plazo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fiado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('fechainventario', models.DateField(db_column='fechaInventario', primary_key=True, serialize=False)),
                ('stockcritico', models.IntegerField(db_column='stockCritico')),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idrepartidor', models.AutoField(db_column='idRepartidor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apaterno', models.CharField(max_length=15)),
                ('amaterno', models.CharField(blank=True, max_length=15, null=True)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'repartidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idtipo', models.IntegerField(db_column='idTipo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('pass_field', models.CharField(db_column='pass', max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(db_column='idVenta', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
