# Generated by Django 3.2 on 2021-07-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210708_1820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
