/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yuyitos.ch.view;

import com.yuyitos.ch.dao.LoginDAO;
import com.yuyitos.ch.db.Conexion;
import com.yuyitos.ch.db.LoginM;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tavo-
 */
public class Login extends javax.swing.JFrame {
    LoginM lg = new LoginM();
    LoginDAO login = new LoginDAO();
       Conexion cn = new Conexion();
    Connection con;
    
    PreparedStatement pst;
    ResultSet rs;
        
    public Login() {
        
        initComponents();
        this.setLocationRelativeTo(null);//para poner a la izquierda
        
        ModificarImagen(lblImagen4, "src/com/yuyitos/ch/imagenes/61355.PNG");//metodo para que la imagen se ajuste al label
        
        ModificarImagen(lblImagen3, "src/com/yuyitos/ch/imagenes/LOGOYUYITOS.PNG");
        
    }
    
    public void Validar(){
        String correo = txtCorreo.getText();
        String pass = String.valueOf(txtPass.getPassword());
        String cargo="";
        if(!"".equals(correo) || !"".equals(pass)){

            lg = login.log(correo, pass);
            if (lg.getCorreo() != null && lg.getPass() != null) {
                            try {
                            String sql="select cargo from usuarios where correo=?";       
                             con=cn.getConnection();
                              pst = con.prepareStatement(sql);//recordar hacer esto antes de cualquier pst.setint o similar porque da nullpointer exception
                              pst.setString(1, lg.getCorreo());
                                ResultSet rs1 = pst.executeQuery();

                                if (rs1.next()){
                                    cargo=rs1.getString(1);
                                    JOptionPane.showMessageDialog(null, cargo);
                                }
                                 if ("Administrador".equals(cargo)){
                        JOptionPane.showMessageDialog(null, "correcto");
                        MenuPrincipal menu = new MenuPrincipal();
                        menu.setVisible(true);
                        //menu.ocultarbodeguero();
                        dispose();
                    }else if("Cajero".equals(cargo)){
                            JOptionPane.showMessageDialog(null, "correcto");
                            MenuPrincipal menu = new MenuPrincipal();
                            menu.setVisible(true);
                            menu.ocultarCajero();
                            dispose();
                        }else if("Bodeguero".equals(cargo)){
                            JOptionPane.showMessageDialog(null, "correcto");
                            MenuPrincipal menu = new MenuPrincipal();
                            menu.setVisible(true);
                            menu.ocultarbodeguero();
                            dispose();
                        }

                                
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.toString());
                        }
                   
                
            }else{
               JOptionPane.showMessageDialog(null, "Correo o contraseña incorrecta");
            }
        }
    }
    
    public void ModificarImagen(JLabel label, String linkImagen){
        ImageIcon imagen = new ImageIcon(linkImagen);
        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(label.getWidth(), label.getHeight(),Image.SCALE_DEFAULT));//lblImagen es igual al nombre del label que contiene la imagen del logo
        label.setIcon(icono);
        this.repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Correo electronico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 170, 50));

        btnValidar.setText("Iniciar sesión");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 36)); // NOI18N
        jLabel4.setText("Almacen");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 234, -1));

        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yuyitos/ch/imagenes/61355.png"))); // NOI18N
        lblImagen4.setText("jLabel6");
        lblImagen4.setToolTipText("");
        jPanel2.add(lblImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 150));

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yuyitos/ch/imagenes/LOGOYUYITOS.PNG"))); // NOI18N
        lblImagen3.setText("jLabel6");
        jPanel2.add(lblImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 480));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 36)); // NOI18N
        jLabel3.setText("Los YUYITOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 270, 60));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 170, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yuyitos/ch/imagenes/el-fondo-gris-suave-del-bokeh-toma-imágenes-con-la-cámara-digital-modifica-colores-para-requisitos-particulares-photoshop-151781646.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_btnValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
